name:                yesod-job-queue
version:             0.4.0.0
synopsis:            Background jobs library for Yesod.
description:
  Background jobs library for Yesod
  .
  * It contains management API and web interface.
  * Queue backend is Redis.
  * Support cron scheduler
  .
  Usage and screen shot are available in README.md

homepage:            https://github.com/nakaji-dayo/yesod-job-queue#readme
license:             BSD3
license-file:        LICENSE
author:              Daishi Nakajima
maintainer:          nakaji.dayo@gmail.com
copyright:           2016 Daishi Nakajima
category:            Web
build-type:          Custom
extra-source-files:
  - README.md
  - doc/yesod-job-queue-ss.png

custom-setup:
  dependencies:
  - base >= 4.7
  - directory >= 1.3.6
  - process >= 1.6.9
  - Cabal

dependencies:
- base >= 4.7
- aeson >= 0.6
- api-field-json-th >= 0.1
- bytestring
- cron >= 0.6.0
- file-embed
- hedis
- monad-logger
- stm
- text
- time
- transformers
- unliftio-core >= 0.1.2.0
- uuid
- yesod >= 1.6
- yesod-core >= 1.6
- yesod-persistent >= 1.6


# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  exposed-modules:
  - Yesod.JobQueue
  - Yesod.JobQueue.GenericConstr
  - Yesod.JobQueue.Routes
  - Yesod.JobQueue.Scheduler
  - Yesod.JobQueue.Types
  default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  yesod-job-queue-example:
    main: Main.hs
    source-dirs: example
    default-extensions:
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - TypeFamilies
    - GADTs
    - MultiParamTypeClasses
    - EmptyDataDecls
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fwarn-tabs
    dependencies:
    - base >= 4.7
    - yesod
    - yesod-core
    - yesod-job-queue
    - persistent-sqlite
    - resourcet
    - monad-logger
    - classy-prelude-yesod
    - hedis
    when:
    - condition: (flag(example))
      then:
        buildable: true
      else:
        buildable: false
#
# Test suite
tests:
  yesod-job-queue-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - base
    - yesod-job-queue
    #- hspec >=2.0.0
    #- yesod-test
    #- microlens


flags:
  example:
    description: Build the example application
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
